"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, BookOpen, Check, CheckCircle2, Circle, Clipboard, GitFork, Lightbulb, Sparkles, Trophy } from "lucide-react";
import { useLab } from "./lab-provider";
import { Badge, PageHeading, ProgressBar, ExternalLink } from "./ui";
import { canComplete, emptyProgress, practiceCorrect, requirements, scoreQuiz } from "@/lib/progress";
import { missions } from "@/data/curriculum";
import { resources } from "@/data/resources";
import type { Mission } from "@/lib/types";
import { BrowserWorkbench } from "./browser-workbench";
const steps = ["Learn", "Practice", "Build", "Quiz", "Prove", "Reflect"];
export function MissionWorkspace({ mission }: { mission: Mission }) {
  const { state, ready, updateMission, complete, notify } = useLab(); const progress = state.missions[mission.id] ?? emptyProgress();
  const [answerDraft, setAnswer] = useState<string | null>(null); const answer = answerDraft ?? progress.practiceAnswer; const [feedback, setFeedback] = useState(""); const [hint, setHint] = useState(0); const [showDebug, setShowDebug] = useState(false);
  const [answers, setAnswers] = useState<number[]>([]); const [submitted, setSubmitted] = useState(false); const [celebrate, setCelebrate] = useState(false);
  const step = progress.step; const criteria = requirements(mission, progress); const percent = Math.round(criteria.filter(r => r.done).length / criteria.length * 100);
  const nextMission = missions[missions.indexOf(mission) + 1]; const lastAttempt = progress.attempts.at(-1);
  const go = (next: number) => updateMission(mission.id, { step: next });
  async function copy(text: string) { try { await navigator.clipboard.writeText(text); notify("Copied. Take it to your VS Code terminal."); } catch { notify("Select the code and copy it with Ctrl+C."); } }
  function Code({ code, language }: { code: string; language: string }) { return <div className="code-block"><header><span>{language}</span><button onClick={() => copy(code)}><Clipboard size={13}/>Copy</button></header><pre><code>{code}</code></pre></div>; }
  function submitQuiz() { if (mission.quiz.some((_,i) => answers[i] === undefined)) return; const score = scoreQuiz(mission, answers); updateMission(mission.id, { attempts: [...progress.attempts.slice(-49), { score, answers, date: new Date().toISOString() }] }); setSubmitted(true); }
  if (!ready) return <div className="loading-state">Opening your mission…</div>;
  if (step === 2) return <BrowserWorkbench key={mission.id} mission={mission} progress={progress} onBack={() => go(1)} onContinue={() => go(3)} onTaskChange={(index, checked) => updateMission(mission.id, { tasks: checked ? [...progress.tasks, index] : progress.tasks.filter(task => task !== index) })} onNotesChange={buildNotes => updateMission(mission.id, { buildNotes })} />;
  return <div className="page"><Link href="/" className="back-link"><ArrowLeft size={14}/>Back to my workspace</Link><PageHeading eyebrow={`LEVEL ${mission.level} · ${mission.skill.toUpperCase()}`} title={mission.title} description={mission.subtitle}><Badge tone="green">{mission.minutes} min · original lesson</Badge></PageHeading>
    {celebrate ? <div className="card celebration"><div className="celebration-icon"><Trophy size={36}/></div><h2>You made something real.</h2><p>Your lesson, practice, build evidence, checkpoint, and reflection are saved. These are learning milestones; your build and challenge evidence are self-reported.</p><div className="action-row" style={{justifyContent:"center"}}><Link href={nextMission ? `/mission/${nextMission.id}` : "/portfolio"} className="button primary">{nextMission ? "See my next mission" : "Review my portfolio"}<ArrowRight size={17}/></Link><Link className="button secondary" href="/">That’s enough for today</Link><button className="text-button" onClick={() => setCelebrate(false)}>Review this mission</button></div></div> : <div className="mission-layout"><div className="mission-main"><nav className="mission-tabs" aria-label="Mission steps">{steps.map((label,i) => <button key={label} aria-current={step===i?"step":undefined} className={step===i?"active":""} onClick={() => go(i)}><span>{String(i+1).padStart(2,"0")}</span>{label}</button>)}</nav>
      <article className="card mission-panel">
      {step===0 && <><Badge tone="green">01 · UNDERSTAND</Badge><h2 className="small-heading">Start with the idea.</h2><ul className="list-clean">{mission.objectives.map(o=><li key={o}><CheckCircle2 size={17}/>{o}</li>)}</ul>{mission.lesson.map(section=><section className="lesson-section" key={section.title}><h3>{section.title}</h3><p>{section.body}</p></section>)}<Code code={mission.code} language={mission.language}/>{mission.level===0 && <div className="notice">Missing a tool? Use <a href="https://code.visualstudio.com/download" target="_blank" rel="noreferrer">VS Code</a>, <a href="https://git-scm.com/downloads" target="_blank" rel="noreferrer">Git</a>, or <a href="https://www.python.org/downloads/" target="_blank" rel="noreferrer">Python</a>. Choose F: for installations where the installer supports it. Reopen your terminal after installing. If py is unavailable but python --version works, use python.</div>}{mission.level===1 && <div className="notice">If Git asks who you are, set git config user.name and git config user.email for this repository using your chosen name and GitHub email. Use the private commit email in GitHub settings if preferred. Use your real repository URL in place of YOUR_REPOSITORY_URL.</div>}<div className="action-row"><button className="button primary" onClick={()=>{updateMission(mission.id,{learned:true,step:1});}}>I understand. Let me try.<ArrowRight size={17}/></button></div></>}
      {step===1 && <><Badge tone="green">02 · PRACTICE</Badge><h2 className="small-heading">Think first. Then check.</h2><p>{mission.practice.prompt}</p><label className="field">Your answer<input value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Try an answer. Mistakes are part of this." autoComplete="off" maxLength={500}/></label><div className="action-row"><button className="button primary" disabled={!answer.trim()} onClick={()=>{const correct=practiceCorrect(mission,answer);updateMission(mission.id,{practiceAnswer:answer,practicePassed:correct});setFeedback(correct?mission.practice.explanation:"Not quite yet. Read the question again or reveal a hint, then try another answer.");}}>Check my answer</button><button className="button secondary" disabled={hint>=mission.practice.hints.length} onClick={()=>setHint(h=>h+1)}><Lightbulb size={16}/>One small hint</button></div>{feedback&&<div role="status" className={`feedback ${progress.practicePassed?"":"wrong"}`}>{progress.practicePassed&&<Check size={16}/>} {feedback}</div>}{hint>0&&<ol className="hint-list">{mission.practice.hints.slice(0,hint).map(h=><li key={h}>{h}</li>)}</ol>}<div className="divider"/><h3>Debug detective</h3><Code code={mission.debug.code} language="Find the problem"/><p>{mission.debug.question}</p><button className="text-button" onClick={()=>setShowDebug(s=>!s)}>{showDebug?"Hide explanation":"Show the explanation after thinking it through"}</button>{showDebug&&<div className="feedback">{mission.debug.explanation}</div>}<p className="provider-note">This checks your answer. Run code in the browser workspace on the next step.</p><div className="action-row"><button className="button primary" onClick={()=>go(2)}>Go to my build<ArrowRight size={17}/></button></div></>}
      {step===2 && <><Badge tone="green">03 · BUILD</Badge><h2 className="small-heading">Make it work on your computer.</h2><p>Work through these in VS Code. Check a task when you have done it yourself.</p>{mission.tasks.map((task,i)=><label key={task} className="task-check"><input type="checkbox" checked={progress.tasks.includes(i)} onChange={e=>updateMission(mission.id,{tasks:e.target.checked?[...progress.tasks,i]:progress.tasks.filter(n=>n!==i)})}/><span>{task}</span></label>)}<div className="coach-box"><h3><Sparkles size={17}/>A useful prompt for your VS Code agent</h3><p>“I’m learning to {mission.title.toLowerCase()}. Ask me to predict the result. Give one hint at a time. Help me read errors, then ask me to explain why the fix works. Let me write the code.”</p><button className="text-button" onClick={()=>copy(`I'm learning to ${mission.title.toLowerCase()}. Ask me to predict the result. Give one hint at a time. Help me read errors, then ask me to explain why the fix works. Let me write the code.`)}>Copy coaching prompt</button></div><label className="field">My build notes and actual output<textarea value={progress.buildNotes} maxLength={10000} onChange={e=>updateMission(mission.id,{buildNotes:e.target.value})} placeholder="Paste your real terminal output, the cases you tried, and what happened. At least 40 characters."/><small>Saved automatically in this browser. Do not paste passwords or API keys.</small></label><div className="action-row"><button className="button primary" onClick={()=>go(3)}>Check my understanding<ArrowRight size={17}/></button></div></>}
      {step===3 && <><Badge tone="green">04 · CHECKPOINT</Badge><h2 className="small-heading">Can you explain what you built?</h2><p>Five questions. Pass with 80%. Your build and reflection also count toward completion.</p>{lastAttempt&&!submitted&&<div className="notice">Last score: {lastAttempt.score}% · {progress.attempts.length} attempt{progress.attempts.length===1?"":"s"}. A new attempt replaces the score used for this mission.</div>}{mission.quiz.map((question,i)=><fieldset className="quiz-question" key={question.prompt}><legend>{i+1}. {question.prompt}</legend>{question.options.map((option,j)=><label className="quiz-option" key={option}><input type="radio" name={`question-${i}`} disabled={submitted} checked={answers[i]===j} onChange={()=>setAnswers(a=>{const next=[...a];next[i]=j;return next;})}/>{option}</label>)}{submitted&&<div className={`feedback ${answers[i]===question.answer?"":"wrong"}`}><strong>{answers[i]===question.answer?"Correct. ":"Review this idea. "}</strong>{question.explanation}</div>}</fieldset>)}{submitted&&lastAttempt&&<div className="quiz-result" role="status"><h3>{lastAttempt.score}% · {lastAttempt.score>=80?"Checkpoint passed":"A little more practice"}</h3><p>{lastAttempt.score>=80?"Now connect your answers to the work you actually built.":"Review the explanations and your lesson. Try explaining a wrong answer before retrying."}</p></div>}<div className="action-row">{!submitted?<button className="button primary" disabled={mission.quiz.some((_,i)=>answers[i]===undefined)} onClick={submitQuiz}>Submit my answers</button>:<><button className="button secondary" onClick={()=>{setSubmitted(false);setAnswers([]);}}>Try the checkpoint again</button><button className="button primary" onClick={()=>go(4)}>Add my evidence<ArrowRight size={17}/></button></>}</div><p className="provider-note">A Lab practice check, not an official certification exam.</p></>}
      {step===4 && <><Badge tone="green">05 · PROVE IT</Badge><h2 className="small-heading">Let your work tell the story.</h2><p>{mission.level===0?"Your first mission starts with a local learning log. You’ll publish it in the next mission.":"Push your work to your own repository and give another person enough information to run it."}</p><label className="field">GitHub repository {mission.level===0?"(optional for this mission)":"(required)"}<input type="url" value={progress.repository} maxLength={300} onChange={e=>updateMission(mission.id,{repository:e.target.value})} placeholder="https://github.com/your-name/ai-learning-lab"/><small>Use the repository homepage, not an individual file link.</small></label><div className="coach-box"><h3><GitFork size={18}/>Your evidence checklist</h3><ul className="list-clean"><li><Check size={15}/>README: what it does and how to run it</li><li><Check size={15}/>Code or files you actually created</li><li><Check size={15}/>Real output, checks, and lessons learned</li><li><Check size={15}/>A descriptive commit explaining the change</li></ul></div><Link className="text-link" href="/portfolio">Check a public repository in your portfolio<ArrowRight size={15}/></Link><p className="provider-note">A saved URL alone is not verification. The portfolio can check public repository metadata and README availability.</p><div className="action-row"><button className="button primary" onClick={()=>go(5)}>Reflect & finish<ArrowRight size={17}/></button></div></>}
      {step===5 && <><Badge tone="green">06 · MAKE IT YOURS</Badge><h2 className="small-heading">One more step, without the tutorial.</h2><div className="coach-box"><h3><Trophy size={18}/>Your independent challenge</h3><p>{mission.boss}</p></div><label className="field">What I tried independently<textarea value={progress.bossNotes} onChange={e=>updateMission(mission.id,{bossNotes:e.target.value})} maxLength={10000} placeholder="Record your approach, real result, and anything you needed help with. At least 30 characters."/></label><label className="field">{mission.reflection}<textarea value={progress.reflection} onChange={e=>updateMission(mission.id,{reflection:e.target.value})} maxLength={10000} placeholder="Use your own words. At least 30 characters."/></label><p className="provider-note">No rush. A clear explanation is more valuable than a checked box.</p><div className="action-row"><button className="button primary" disabled={!canComplete(mission,progress)} onClick={()=>{if(complete(mission.id))setCelebrate(true);}}><CheckCircle2 size={17}/>{progress.completedAt?"Save & celebrate":"Complete this mission"}</button></div>{!canComplete(mission,progress)&&<p className="provider-note">The checklist shows what still needs your attention.</p>}</>}
      </article><div className="action-row">{step>0&&<button className="button secondary" onClick={()=>go(step-1)}><ArrowLeft size={15}/>Previous step</button>}<Link href="/" className="text-link">Save my place and take a break</Link></div>
    </div><aside className="mission-aside"><div className="card"><div className="card-heading"><BookOpen size={19}/><h2>Your mission checklist</h2></div><div className="progress-caption"><strong>{criteria.filter(r=>r.done).length} of {criteria.length} complete</strong><span>{percent}%</span></div><ProgressBar value={percent} label="Mission completion criteria"/><ul className="criteria">{criteria.map((r,i)=><li className={r.done?"checked":""} key={i}>{r.done?<CheckCircle2 size={15}/>:<Circle size={15}/>}<span>{r.label}</span></li>)}</ul><div className="divider"/><h3 style={{fontSize:14}}>Need a smaller step?</h3><p className="provider-note">Spend just 10 minutes on the current section. Your notes and completed tasks are saved as you go.</p><div className="divider"/><Badge>Guided hints available</Badge><p className="provider-note">Hints are written for this mission. A live AI tutor is a later milestone.</p></div></aside></div>}
  </div>;
}
